### ISSUE TITLE
Separar cliente do servidor

### ISSUE THREAD

**Issue by jesuino** [Jug-Vale/jug-call4papers#71]
Issue urgente para a versão 2.0 - separar o servidor do cliente. Criar estrutura semelhante a seguinte:

- jug-cfp-server
- jug-cfp-client
    - jug-cfp-gwt
    - jug-cfp-app
    - jug-cfp-legado

O legado teria a WEB de hoje, mantido somente para termos um cliente funcional, mas o objetivo é apagar na versão 2 GA, quando teremos um cliente funcional.

**Comment by pedro-hos** [comment]
Qual seria a diferença entre: jug-cfp-gwt e jug-cfp-app?

**Comment by jesuino** [comment]
A jug-cfp-app seria uma aplicação que instalaríamos em um totem que ficaria no evento para as pessoas marcarem presença e se inscriever. Vamos montar o totem com o tempo.

A prioridade, no entanto, é a aplicação web mais moderna com GWT e a modernização do servidor para usar microprofile
